name: DAST
on:
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]
jobs:
  dast:
  - name: Run Dastardly Action Step
    uses: PortSwigger/dastardly-github-action@main
    with:
      target-url: 'http://35.81.32.236:3000/'
