name: Nuclei

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: http://testaspnet.vulnweb.com/

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log

      - name: GitHub Security Dashboard Alerts update
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: nuclei.sarif

          
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: nuclei.sarif
          path: nuclei.sarif
          
  import:
    name: Conviso Findings Importation
    needs: nuclei-scan
    runs-on: ubuntu-20.04
    container:
      image: convisoappsec/flowcli
      env:
        FLOW_API_KEY: ${{ secrets.CONVISO_API_KEY }}
        FLOW_API_URL: ${{ secrets.HOMOLOGA_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download result from previous scan
        uses: actions/download-artifact@v3
        with:
          name: nuclei.sarif

      - name: SARIF Importation
        run: |
          conviso findings import-sarif --input-file nuclei.sarif
